# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplayer.proto\x12\x08xTimpact\"\xaf\x01\n\x06player\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\x12(\n\txT_attack\x18\x03 \x03(\x0b\x32\x15.xTimpact.player.game\x1aS\n\x04game\x12\x0f\n\x07game_id\x18\x01 \x01(\x02\x12\x11\n\txT_impact\x18\x02 \x01(\x02\x12\x16\n\x0eminutes_player\x18\x03 \x01(\x05\x12\x0f\n\x07starter\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYER._serialized_start=27
  _PLAYER._serialized_end=202
  _PLAYER_GAME._serialized_start=119
  _PLAYER_GAME._serialized_end=202
# @@protoc_insertion_point(module_scope)
